[package]
name = "libevent"
version = "0.0.0"
authors = ["Jon Magnuson <jon.magnuson@gmail.com>"]
description = "Rust bindings to the libevent async I/O framework"
repository = "https://github.com/jmagnuson/libevent-rs"
license = "MIT/Apache-2.0"
edition = "2018"

[features]
default = [ "threading" ]
static = [ "libevent-sys/static" ]
bundled = [ "static", "libevent-sys/bundled" ]
threading = [ "libevent-sys/threading" ]

[dependencies]
libevent-sys = { version = "0.2", path = "libevent-sys" }
