[package]
name = "hello"
version = "0.1.0"
authors = ["Jon Magnuson <jon.magnuson@gmail.com>"]
edition = "2018"
build="build.rs"

[dependencies]
libevent-sys = { path = "../../libevent-sys", features = [ "bundled" ] }
libevent = { path = "../../", features = [ "bundled" ] }

[build-dependencies]
cmake = "0.1"
